// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} chatbotApiUrl
 * @param {string} apiKey
 * @param {string} toggleButtonColor
 * @param {string} agentAvatarUrl
 * @param {string} homeScanId
 * @param {string} agentSessionId
 * @returns {Promise.<void>}
 */
export async function JS_LoadAiAdvisor(chatbotApiUrl, apiKey, toggleButtonColor, agentAvatarUrl, homeScanId, agentSessionId) {
	// BEGIN USER CODE
	const CSS_URL = "https://homezerotech.github.io/files/salesagent/widget.css";
	    const JS_URL = "https://homezerotech.github.io/files/salesagent/widget.js";
	
	    loadCss(CSS_URL, "salesagent-widget-css");
	
	    try {
	        console.log("[ChatWidget Debug] Starting load process...");
	        await loadScript(JS_URL, "salesagent-widget-js");
	
	        const ChatWidgetObj = await waitForGlobal("ChatWidget", 3000);
	
	        if (ChatWidgetObj && typeof ChatWidgetObj.init === "function") {
	            const config = {
	                chatbotApiUrl: chatbotApiUrl,
	                apiKey: apiKey,
	                toggleButtonColor: toggleButtonColor || "#94fc1c",
	                toggleButtonIconColor: "white"
	            };
	
	            if (agentAvatarUrl && agentAvatarUrl.trim() !== "") {
	                config.agentAvatarUrl = agentAvatarUrl;
	            }
	
	            if (homeScanId && homeScanId.trim() !== "") {
	                config.homeScanId = homeScanId;
	            }
	
	            if (agentSessionId && agentSessionId.trim() !== "") {
	                config.sessionId = agentSessionId;
	            }
	
	            console.log("[ChatWidget Debug] Initializing widget with config:", config);
	            ChatWidgetObj.init(config);
	        } else {
	            console.error("[ChatWidget Debug] ChatWidget found but missing .init() method:", ChatWidgetObj);
	        }
	    } catch (error) {
	        console.error("[ChatWidget Debug] Initialization failed:", error);
	    }
	// END USER CODE
}
